### ISSUE TITLE
Console spams "BLockTypes have not been read!"

### ISSUE THREAD

**Issue by PureTryOut** [linuxmasterrace/Townvalds#26]
Every once and while, the console spams the following:

```
[13:43:55] cBlockArea: BlockTypes have not been read!
[13:43:55] cBlockArea: BlockTypes have not been read!
[13:43:55] cBlockArea: BlockTypes have not been read!
```

The amount of lines changes per time it happens.

This is probably caused by #19

**Comment by omarroth** [comment]
I'm having trouble reproducing it, roughly how long does it take for these messages to appear?

**Comment by PureTryOut** [comment]
About 5 minutes? Can't really say for certain, it appears to be random.
