### ISSUE TITLE
Town permission control

### ISSUE THREAD

**Issue by PureTryOut** [linuxmasterrace/Townvalds#35]
An permission system for towns. Allow a mayor to set permissions for outsiders, allies and town members to:
- Build blocks
- Break blocks
- Use switches (doors, levers, etc)
- Chest access

**Comment by Avamander** [comment]
Maybe would it also be possible to add item use restriction (flint, chorus, potions and so on)?

If there are additional groups in the town (Assistant, newbie) then it should be possible to restrict per plot/town based on those too.

If possible then per-user restrictions could be added too. Sometimes you don't want that one person to touch anything in the town.
