### ISSUE TITLE
Utilizing Minecraft's scoreboard teams

### ISSUE THREAD

**Issue by Avamander** [linuxmasterrace/Townvalds#36]
Latest Minecraft versions have a new thing called Scoreboard teams. By utilizing the functionality Minecraft offers people in nations could be more easily differentiated by both server and the players.
- Spectral arrows use the team's color for highlighting
- Friendly fire can be toggled on and off
- Suffixes, prefixes for people in the chat
- Commands can be used on entire teams

etc...

http://minecraft.gamepedia.com/Scoreboard#Teams

> Teams
> 
> Teams are a combination of name, display name, prefix, suffix, friendly fire options, and a list of players who are on the team.
> 
> As with objectives, the name and display name of a team are case-sensitive, name is a single word used internally, and display name can be multiple words and does not need to be unique.
> 
> The prefix and suffix are inserted before and after the names of players on a team - without using external editors, the only possible prefixes are formatting codes for team colors, and the only possible suffix is the reset code (so characters after a player's name aren't formatted). Prefixes and suffixes will be added to the names of players in chat, the active players list, the sidebar, and above their heads. Without ingame-option,you may need third-party softwares to edit them.
> 
> The friendly fire option allows control of whether team members can harm each other. Its default mode, "true", makes no changes to PvP mechanics. When set to "false", however, it prevents players on the same team from causing damage to each other with melee attacks, bows, and Splash Potions of Harming. Note that players on the same team may still inflict negative status effects on each other with potions, even if friendly fire is false.
> 
> It is important to note that each individual player can only be on one team; teams cannot share players.
> 
> Command blocks can be used to check whether a player is on a team with the "team" argument; the "!" character may be placed before a name to check for players not on the team. For example, "testfor @p[team=red]" in a Command Block will provide comparator output if a player is on the "red" team. Similarly, "testfor @p[team=!red]" will provide output for players who are not on "red". Also, "testfor @p[team=!]" will check for all players on a team, while "testfor @p[team=] will check for those without a team.

**Comment by PureTryOut** [comment]
I looked into this a bit. Teams are made in cTeam, but according to [this](https://forum.cuberite.org/thread-2370.html) thread, it's only available per world.

This kinda defeats the point of what we want here, as you would lose your team when you enter the Nether or the End. Of course we can still divide players into nations automatically, and give them all a seperate spawn, etc. But we would be missing the integration with Minecraft itself.

**Comment by Avamander** [comment]
But would it not be possible to just recreate the teams for every world? Making sure they all sync up in all three worlds.

**Comment by PureTryOut** [comment]
Probably, but a bit more of a hassle. I'm not sure if we can just get the cWorld object of every world like that.

**Comment by random-nick** [comment]
You can always use [cRoot](http://api-docs.cuberite.org/cRoot.html):Get():ForEachWorld to do something for each world.

**Comment by PureTryOut** [comment]
I'm busy with this now, look out for the pull request soon

**Comment by PureTryOut** [comment]
Update, I'm fairly on the way of making this. However, I'm waiting for [this](https://github.com/cuberite/cuberite/issues/3210) issue on Cuberite to complete.

**Comment by PureTryOut** [comment]
Basically done in #41 . Waiting for @random-nick to merge it.
