### ISSUE TITLE
TownChunks when claimed in The Overworld are claimed in The Nether and The End too

### ISSUE THREAD

**Issue by random-nick** [linuxmasterrace/Townvalds#40]
When you claim a chunk in The Overworld, and then go to the same chunk in another world you will still get the message that you are entering the town and won't be able to break blocks if you lack permission.

**Comment by Avamander** [comment]
How exactly does it work in nether? Is chunk -1;-1 claimed in overworld also marked claimed in nether (also chunk -1;-1)?

You just reminded me that currently Towny does not deal with two things, but it should:
a) Claiming nether chunks that that are adjacent to claimed overworld chunks should be possible. Makes it both possible to create protected nether buildings.and securing portals from mob griefing.
b) Making portals that would take you to a claimed area would not be possible unless the player has the rights.

**Comment by random-nick** [comment]
@Avamander
Yes, chunk -1;-1 is claimed in all worlds if claimed in one.
Also, for your point a I don't think it should work like that, I think it should be divided by 8 because of how nether portals route.

**Comment by Avamander** [comment]
I meant adjacent as in coordinates not chunks.

**Comment by PureTryOut** [comment]
Didn't think about this yet, the chunks should be saved per world I guess.
Should be a small fix.

@Avamander for your point A, I would think you could allow towns to claim one random chunk in the nether, and make the next chunks be adjacent to that one. There could be a config option to allow this. Maybe both and let users switch between them with a config option?

**Comment by Avamander** [comment]
Yeah, that sounds reasonable. Currently with Towny using nether you could
easily just spam portals everywhere. That should be preventable.
